/*
 * Copyright (C) 2012-2016 NS Solutions Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
 //
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.09 at 11:04:48 午前 JST 
//


package com.htmlhifive.tools.codeassist.core.config.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="controller" type="{}controller" minOccurs="0"/>
 *         &lt;element name="logic" type="{}logic" minOccurs="0"/>
 *         &lt;element name="eventcontext" type="{}eventcontext" minOccurs="0"/>
 *         &lt;element name="initcontext" type="{}InitializationContext" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "controller",
    "logic",
    "eventcontext",
    "initcontext"
})
@XmlRootElement(name = "h5-code-assist")
public class H5CodeAssist {

    protected Controller controller;
    protected Logic logic;
    protected Eventcontext eventcontext;
    protected InitializationContext initcontext;

    /**
     * Gets the value of the controller property.
     * 
     * @return
     *     possible object is
     *     {@link Controller }
     *     
     */
    public Controller getController() {
        return controller;
    }

    /**
     * Sets the value of the controller property.
     * 
     * @param value
     *     allowed object is
     *     {@link Controller }
     *     
     */
    public void setController(Controller value) {
        this.controller = value;
    }

    /**
     * Gets the value of the logic property.
     * 
     * @return
     *     possible object is
     *     {@link Logic }
     *     
     */
    public Logic getLogic() {
        return logic;
    }

    /**
     * Sets the value of the logic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Logic }
     *     
     */
    public void setLogic(Logic value) {
        this.logic = value;
    }

    /**
     * Gets the value of the eventcontext property.
     * 
     * @return
     *     possible object is
     *     {@link Eventcontext }
     *     
     */
    public Eventcontext getEventcontext() {
        return eventcontext;
    }

    /**
     * Sets the value of the eventcontext property.
     * 
     * @param value
     *     allowed object is
     *     {@link Eventcontext }
     *     
     */
    public void setEventcontext(Eventcontext value) {
        this.eventcontext = value;
    }

    /**
     * Gets the value of the initcontext property.
     * 
     * @return
     *     possible object is
     *     {@link InitializationContext }
     *     
     */
    public InitializationContext getInitcontext() {
        return initcontext;
    }

    /**
     * Sets the value of the initcontext property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitializationContext }
     *     
     */
    public void setInitcontext(InitializationContext value) {
        this.initcontext = value;
    }

}
