/*
 * Copyright (C) 2012 NS Solutions Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
 //
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.09 at 11:04:48 午前 JST 
//


package com.htmlhifive.tools.codeassist.core.config.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.htmlhifive.tools.codeassist.core.config.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.htmlhifive.tools.codeassist.core.config.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link H5CodeAssist }
     * 
     */
    public H5CodeAssist createH5CodeAssist() {
        return new H5CodeAssist();
    }

    /**
     * Create an instance of {@link Controller }
     * 
     */
    public Controller createController() {
        return new Controller();
    }

    /**
     * Create an instance of {@link Logic }
     * 
     */
    public Logic createLogic() {
        return new Logic();
    }

    /**
     * Create an instance of {@link Eventcontext }
     * 
     */
    public Eventcontext createEventcontext() {
        return new Eventcontext();
    }

    /**
     * Create an instance of {@link InitializationContext }
     * 
     */
    public InitializationContext createInitializationContext() {
        return new InitializationContext();
    }

    /**
     * Create an instance of {@link VarReference }
     * 
     */
    public VarReference createVarReference() {
        return new VarReference();
    }

    /**
     * Create an instance of {@link Variable }
     * 
     */
    public Variable createVariable() {
        return new Variable();
    }

    /**
     * Create an instance of {@link Function }
     * 
     */
    public Function createFunction() {
        return new Function();
    }

}
